#!/bin/sh
set -e
. /etc/profile
exec /usr/bin/java \
  -Djava.awt.headless=true \
  -Dlogback.configurationFile=/opt/housing/logback.xml \
  -jar /opt/housing/housing.jar \
  >> /var/log/housing/housing.log 2>&1
