#!/bin/sh
. /etc/profile
set -eu
JAVA=${JAVA_HOME:-/usr}/bin/java

exec "$JAVA" \
  -XX:+UseParallelGC \
  -XX:MinHeapFreeRatio=20 \
  -XX:MaxHeapFreeRatio=40 \
  -XX:GCTimeRatio=10 \
  -XX:AdaptiveSizePolicyWeight=90 \
  -Djava.awt.headless=true \
  -Dlogback.configurationFile=/opt/housing/logback.xml \
  -jar /opt/housing/housing.jar \
  >> /var/log/housing/housing.log 2>&1
