package scot.mygov.housing.forms.noticetoleave.model;

public enum Reason {

    LANDLORD_TO_SELL,
    LENDER_TO_SELL,
    LANDLORD_TO_REFURBISH,
    LANDLORD_TO_LIVE,
    LANDLORD_FAMILY_MEMBER_TO_LIVE,
    LANDLORD_NON_RESIDENTIAL_PURPOSE,
    RELIGIOUS,
    YOU_CEASE_TO_BE_EMPLOYEE,
    YOU_NO_LONGER_NEED_SUPPORTED_ACC,
    YOU_NO_LONGER_OCCUPY,
    YOU_BREACHED_TERMS,
    YOU_RENT_ARREARS,
    YOU_CRIMINAL_CONVICTION,
    YOU_ANTISOCIAL_BEHAVIOUR,
    YOU_ASSOCIATED_CONVICTION_OR_ANTISOCIAL,
    LANDLORD_REGISTRATION_REVOKED,
    LANDLORD_HMO_REFUSED,
    LANDLORD_OVERCROWDING_NOTICE;
}
